services:
  identity_broker:
    container_name: identity_broker
    image: quay.io/keycloak/keycloak:26.1
    command: ["start-dev"] # "--http-port", "8080"
    # ports:
    #   - 8081:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=secret
      # - KEYCLOAK_ADMIN=admin
      # - KEYCLOAK_ADMIN_PASSWORD=secret
      # - KC_HOSTNAME=localhost
      # - KC_HOSTNAME_PORT=8090
      # - KC_HOSTNAME_STRICT_BACKCHANNEL=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.identity_broker.rule=Host(`identity-broker.docker.localhost`)"
    networks:
      - keycloakNet

  service_provider:
    container_name: service_provider
    build:
      context: ./serviceProvider
      dockerfile: Dockerfile
    # ports:
    #   - 8080:8080
    volumes:
      - ./serviceProvider:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.service_provider.rule=Host(`service-provider.docker.localhost`)"
    # network_mode: host
    networks:
      - keycloakNet

  traefik_proxy:
    container_name: traefik_proxy
    image: traefik:v3.3.2
    ports:
      - 9000:80
      - 9001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - keycloakNet

  nginx_proxy:
    container_name: nginx_proxy
    image: nginx:1.21.3
    # ports:
      # - 8080:8080
      # - 8081:8081
    volumes:
      - ./nginxProxy/nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "traefik.enable=false"
    networks:
      - keycloakNet

networks:
  keycloakNet:
    driver: bridge
